bghb/config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from countries.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bghb.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("countries/", include("countries.urls", namespace="countries")),
    path("documents/", include("documents.urls", namespace="documents")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bghb/countries/urls.py
from django.urls import path
from .views import CountryListView, CountryDetailView, CountryCreateView, CountryUpdateView

# namespaces = 'countries'
app_name = 'countries'  

urlpatterns = [
    path('', CountryListView.as_view(), name='country_list'),
    path('<int:pk>/', CountryDetailView.as_view(), name='country_detail'),
    path('create/', CountryCreateView.as_view(), name='country_create'),
    path('<int:pk>/update/', CountryUpdateView.as_view(), name='country_update'),
]

bghb/documents/urls.py
from django.urls import path
from .views import *

app_name = 'documents'

urlpatterns = [

    path('<int:pk>/', DocumentTypeDetailView.as_view(), name='document_type_detail'),
    path('<int:country_id>/document-type/add/', DocumentTypeCreateView.as_view(), name='document_type_add'),
    path('document-type/<int:document_id>/feature/add/', DocumentFeatureCreateView.as_view(), name='document_feature_add'),
    path('feature/<int:pk>/edit/', DocumentFeatureUpdateView.as_view(), name='document_feature_edit'),
    path('feature/<int:feature_id>/detail/add/', FeatureDetailCreateView.as_view(), name='feature_detail_add'),
    path('detail/<int:pk>/edit/', FeatureDetailUpdateView.as_view(), name='feature_detail_edit'),
]

bghb/countries/models.py
from django.db import models

# Create your models here.
class Country(models.Model):
    full_name = models.CharField(max_length=255, verbose_name="Полное название страны")
    short_name = models.CharField(max_length=255, verbose_name="Краткое название страны")
    code_3 = models.CharField(max_length=3, verbose_name="Код страны из 3 букв")
    code_2 = models.CharField(max_length=2, verbose_name="Код страны из 2 букв")

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Страна"
        verbose_name_plural = "Страны"


class EntryRegime(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name="Страна")
    regime = models.TextField(verbose_name="Режим въезда в РФ", null=True, blank=True)
    regulatory_legal_acts = models.TextField(verbose_name="Нормативно-правовой акт", null=True, blank=True)
    note = models.TextField(verbose_name="Примечание", blank=True, null=True)

    def __str__(self):
        return f"{self.country.short_name} - {self.regime}"

    class Meta:
        verbose_name = "Режим въезда"
        verbose_name_plural = "Режимы въезда"

bghb/countries/forms.py
from django import forms
from .models import Country, EntryRegime

class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['full_name', 'short_name', 'code_3', 'code_2']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'short_name': forms.TextInput(attrs={'class': 'form-control'}),
            'code_3': forms.TextInput(attrs={'class': 'form-control'}),
            'code_2': forms.TextInput(attrs={'class': 'form-control'}),
        }

class EntryRegimeForm(forms.ModelForm):
    class Meta:
        model = EntryRegime
        fields = ['regime', 'regulatory_legal_acts', 'note']
        widgets = {
            'regime': forms.TextInput(attrs={'class': 'form-control'}),
            'regulatory_legal_acts': forms.TextInput(attrs={'class': 'form-control'}),
            'note': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

bghb/countries/views.py
from django.shortcuts import render
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Country, EntryRegime
from .forms import CountryForm, EntryRegimeForm

from mixins.is_staff_mixin import IsStaffRequiredMixin

from documents.models import DocumentType


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['country_count'] = Country.objects.count()
        context['document_type_count'] = DocumentType.objects.count()
        context['entry_regime_count'] = EntryRegime.objects.count()
        return context


class CountryListView(ListView):
    model = Country
    template_name = 'countries/country_list.html'
    context_object_name = 'countries'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')  # Получаем поисковый запрос
        if query:
            # Ищем по полному и краткому названию страны
            return Country.objects.filter(
                Q(full_name__icontains=query) | Q(short_name__icontains=query)
            )
        return Country.objects.all()  # Если запроса нет, возвращаем все страны


class CountryDetailView(DetailView):
    model = Country
    template_name = 'countries/country_detail.html'
    context_object_name = 'country'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entry_regimes'] = EntryRegime.objects.filter(country=self.object)
        return context


class CountryCreateView(IsStaffRequiredMixin, CreateView):
    model = Country
    form_class = CountryForm
    template_name = 'countries/country_form.html'
    success_url = reverse_lazy('countries:country_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['entry_regime_form'] = EntryRegimeForm(self.request.POST)
        else:
            context['entry_regime_form'] = EntryRegimeForm()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        entry_regime_form = context['entry_regime_form']
        if entry_regime_form.is_valid():
            self.object = form.save()
            entry_regime = entry_regime_form.save(commit=False)
            entry_regime.country = self.object
            entry_regime.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class CountryUpdateView(IsStaffRequiredMixin, UpdateView):
    model = Country
    form_class = CountryForm
    template_name = 'countries/country_form.html'
    # success_url = reverse_lazy('countries:country_detail')
    def get_success_url(self):
        # Получаем только что обновленный объект
        return reverse('countries:country_detail', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['entry_regime_form'] = EntryRegimeForm(self.request.POST, 
                                                           instance=self.object.entryregime_set.first()
                                                           )
        else:
            context['entry_regime_form'] = EntryRegimeForm(instance=self.object.entryregime_set.first())
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        entry_regime_form = context['entry_regime_form']
        if entry_regime_form.is_valid():
            self.object = form.save()
            entry_regime = entry_regime_form.save(commit=False)
            entry_regime.country = self.object
            entry_regime.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))
        

bghb/countries/templates/countries/country_detail.html
{% extends 'base.html' %}

{% block title %}{{ country.full_name }}{% endblock %}

{% block content %}
<h1 class="mb-4">{{ country.full_name }}</h1>
<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">Информация о стране</h5>
        <p class="card-text">Краткое название: {{ country.short_name }}</p>
        <p class="card-text">Код страны (3 буквы): {{ country.code_3 }}</p>
        <p class="card-text">Код страны (2 буквы): {{ country.code_2 }}</p>
    </div>
</div>

<h2 class="mb-3">Режимы въезда</h2>
<ul class="list-group mb-4">
    {% for regime in entry_regimes %}
        <li class="list-group-item">
            {{ regime.regime|safe }} - {{ regime.regulatory_legal_acts|safe }} ({{ regime.note }})
        </li>
    {% endfor %}
</ul>

<h2 class="mb-3">Типы документов</h2>
<ul class="list-group mb-4">
    {% for document_type in country.document_types.all %}
        <li class="list-group-item">
            <a href="{% url 'documents:document_type_detail' document_type.pk %}">
                {{ document_type.name }} ({{ document_type.code }})
            </a>
        </li>
    {% empty %}
        <li class="list-group-item">Нет связанных типов документов.</li>
    {% endfor %}
</ul>

{% if user.is_staff %}
<a href="{% url 'countries:country_update' country.pk %}" class="btn btn-warning">Редактировать</a>
<a href="{% url 'documents:document_type_add' country_id=country.pk %}" class="btn btn-warning">Добавить документ</a>
{% endif %}

{% endblock %}

bghb/countries/templates/countries/country_form.html
{% extends 'base.html' %}

{% block title %}{% if object %}Редактировать страну{% else %}Добавить страну{% endif %}{% endblock %}

{% block content %}
<h1 class="mb-4">{% if object %}Редактировать страну{% else %}Добавить страну{% endif %}</h1>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        {{ form.as_p }}
    </div>
    <h2 class="mb-3">Режим въезда</h2>
    <div class="mb-3">
        {{ entry_regime_form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

bghb/countries/templates/countries/country_list.html
{% extends 'base.html' %}

{% block title %}Список стран{% endblock %}

{% block content %}
<h1 class="mb-4">Список стран</h1>

<!-- Отображение поискового запроса -->
{% if request.GET.q %}
    <p>Результаты поиска для: <strong>{{ request.GET.q }}</strong></p>
{% endif %}

<!-- Список стран -->
<div class="list-group">
    {% for country in countries %}
        <a href="{% url 'countries:country_detail' country.pk %}" class="list-group-item list-group-item-action">
            {{ country.full_name }} ({{ country.short_name }})
        </a>
    {% empty %}
        <p class="text-muted">Страны не найдены.</p>
    {% endfor %}
</div>

<!-- Пагинация (опционально) -->
{% if is_paginated %}
    <nav class="mt-4">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Назад</a>
                </li>
            {% endif %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Вперед</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

{% if user.is_staff %}
<a href="{% url 'countries:country_create' %}" class="btn btn-primary mt-3">Добавить страну</a>
{% endif %}

{% endblock %}