bghb/bghb/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

bghb/config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from countries.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bghb.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("countries/", include("countries.urls", namespace="countries")),
    path("documents/", include("documents.urls", namespace="documents")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bghb/countries/urls.py
from django.urls import path
from .views import CountryListView, CountryDetailView, CountryCreateView, CountryUpdateView

# namespaces = 'countries'
app_name = 'countries'  

urlpatterns = [
    path('', CountryListView.as_view(), name='country_list'),
    path('<int:pk>/', CountryDetailView.as_view(), name='country_detail'),
    path('create/', CountryCreateView.as_view(), name='country_create'),
    path('<int:pk>/update/', CountryUpdateView.as_view(), name='country_update'),
]

bghb/documents/urls.py
from django.urls import path
from .views import *

app_name = 'documents'

urlpatterns = [

    path('<int:pk>/', DocumentTypeDetailView.as_view(), name='document_type_detail'),
    path('<int:country_id>/document-type/add/', DocumentTypeCreateView.as_view(), name='document_type_add'),
    path('document-type/<int:document_id>/feature/add/', DocumentFeatureCreateView.as_view(), name='document_feature_add'),
    path('feature/<int:pk>/edit/', DocumentFeatureUpdateView.as_view(), name='document_feature_edit'),
    path('feature/<int:feature_id>/detail/add/', FeatureDetailCreateView.as_view(), name='feature_detail_add'),
    path('detail/<int:pk>/edit/', FeatureDetailUpdateView.as_view(), name='feature_detail_edit'),
]

bghb/bghb/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for bghb.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

bghb/bghb/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

bghb/documents/forms.py
from django import forms
from .models import DocumentType, DocumentFeature, FeatureDetail

class FeatureDetailForm(forms.ModelForm):
    class Meta:
        model = FeatureDetail
        fields = ['key', 'value', 'image']


class DocumentFeatureForm(forms.ModelForm):
    class Meta:
        model = DocumentFeature
        fields = ['feature_name']


class DocumentTypeForm(forms.ModelForm):
    class Meta:
        model = DocumentType
        fields = [
            'code', 'name', 'category', 'type', 'first_issue_date', 'valid', 
            'legal_status', 'length', 'width', 'pages', 'validity_period', 
            'renewable', 'issuing_country'
        ]

bghb/bghb/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from bghb.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

bghb/bghb/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from bghb.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None=None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

bghb/documents/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DetailView

from countries.models import Country
from .models import DocumentType, DocumentFeature, FeatureDetail
from .forms import DocumentTypeForm, DocumentFeatureForm, FeatureDetailForm
from mixins.is_staff_mixin import IsStaffRequiredMixin
# Create your views here.


class DocumentTypeDetailView(DetailView):
    model = DocumentType
    template_name = 'documents/document_type_detail.html'
    context_object_name = 'document_type'  # Убедитесь, что объект доступен как `document`

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавьте дополнительные данные, если нужно
        return context


class DocumentTypeCreateView(IsStaffRequiredMixin, CreateView):
    model = DocumentType
    form_class = DocumentTypeForm
    template_name = 'documents/document_type_form.html'
    # success_url = '/documents/'  # Укажите URL для перенаправления после успешного создания

    def dispatch(self, request, *args, **kwargs):
        self.country_id = self.kwargs.get('country_id')  # Сохраняем country_id в атрибуте
        return super().dispatch(request, *args, **kwargs)


    def get_initial(self):
        initial = super().get_initial()
        initial['issuing_country'] = self.country_id  # Устанавливаем начальное значение для issuing_country
        return initial
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['country'] = Country.objects.get(pk=self.country_id)  # Добавляем страну в контекст
        return context
    
    def get_success_url(self):
        # Перенаправляем на страницу деталей документа после его создания
        return reverse('documents:document_type_detail', kwargs={'pk': self.object.pk})
    

class DocumentFeatureCreateView(IsStaffRequiredMixin, CreateView):
    model = DocumentFeature
    form_class = DocumentFeatureForm
    template_name = 'documents/document_feature_form.html'

    def dispatch(self, request, *args, **kwargs):
        self.document_id = self.kwargs.get('document_id')  # Сохраняем document_id в атрибуте
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()
        initial['document_type'] = self.document_id  # Устанавливаем начальное значение для document_type
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['document'] = DocumentType.objects.get(pk=self.document_id)  # Добавляем документ в контекст
        return context

    def form_valid(self, form):
        # Связываем особенность с документом
        self.object = form.save(commit=False)
        self.object.document_type_id = self.document_id  # Устанавливаем document_type_id
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Перенаправляем на страницу деталей документа после создания особенности
        return reverse('documents:document_type_detail', kwargs={'pk': self.document_id})


class FeatureDetailCreateView(IsStaffRequiredMixin, CreateView):
    model = FeatureDetail
    form_class = FeatureDetailForm
    template_name = 'documents/feature_detail_form.html'

    def dispatch(self, request, *args, **kwargs):
        self.feature_id = self.kwargs.get('feature_id')  # Сохраняем feature_id в атрибуте
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()
        initial['document_feature'] = self.feature_id  # Устанавливаем начальное значение для document_feature
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feature'] = DocumentFeature.objects.get(pk=self.feature_id)  # Добавляем особенность в контекст
        return context

    def form_valid(self, form):
        # Связываем деталь с особенностью
        self.object = form.save(commit=False)
        self.object.document_feature_id = self.feature_id  # Устанавливаем document_feature_id
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Перенаправляем на страницу деталей документа после создания детали
        feature = DocumentFeature.objects.get(pk=self.feature_id)
        return reverse('documents:document_type_detail', kwargs={'pk': feature.document_type.pk})


class DocumentTypeUpdateView(IsStaffRequiredMixin, UpdateView):
    model = DocumentType
    form_class = DocumentTypeForm
    template_name = 'documents/document_type_form.html'
    success_url = '/documents/'  # Укажите URL для перенаправления после успешного обновления

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['document_feature_form'] = DocumentFeatureForm(self.request.POST, 
                                                                   instance=self.object.features.first())
            context['feature_detail_form'] = FeatureDetailForm(self.request.POST, 
                                                               self.request.FILES, 
                                                               instance=self.object.features.first().details.first())
        else:
            context['document_feature_form'] = DocumentFeatureForm(instance=self.object.features.first())
            context['feature_detail_form'] = FeatureDetailForm(instance=self.object.features.first().details.first())
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        document_feature_form = context['document_feature_form']
        feature_detail_form = context['feature_detail_form']

        if document_feature_form.is_valid() and feature_detail_form.is_valid():
            self.object = form.save()
            document_feature = document_feature_form.save(commit=False)
            document_feature.document_type = self.object
            document_feature.save()

            feature_detail = feature_detail_form.save(commit=False)
            feature_detail.document_feature = document_feature
            feature_detail.save()

            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))
        

class DocumentFeatureUpdateView(IsStaffRequiredMixin, UpdateView):
    model = DocumentFeature
    form_class = DocumentFeatureForm
    template_name = 'documents/document_feature_form.html'
    context_object_name = 'feature'

    def get_success_url(self):
        # Перенаправляем на страницу деталей документа после редактирования
        return reverse('documents:document_type_detail', kwargs={'pk': self.object.document_type.pk})


class FeatureDetailUpdateView(UpdateView):
    model = FeatureDetail
    form_class = FeatureDetailForm
    template_name = 'documents/feature_detail_form.html'
    context_object_name = 'detail'

    def get_success_url(self):
        # Перенаправляем на страницу деталей документа после редактирования
        return reverse('documents:document_type_detail', kwargs={'pk': self.object.document_feature.document_type.pk})

bghb/bghb/templates/documents/document_1type_detail.html
{% extends 'base.html' %}

{% block title %}{{ document_type.name }}{% endblock %}

{% block content %}
<h1 class="mb-4">{{ document_type.name }} ({{ document_type.code }})</h1>

<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">Информация о типе документа</h5>
        <p class="card-text"><strong>Категория:</strong> {{ document_type.category }}</p>
        <p class="card-text"><strong>Тип:</strong> {{ document_type.type }}</p>
        <p class="card-text"><strong>Дата первой выдачи:</strong> {{ document_type.first_issue_date }}</p>
        <p class="card-text"><strong>Действующий:</strong> {{ document_type.valid|yesno:"Да,Нет" }}</p>
        <p class="card-text"><strong>Юридический статус:</strong> {{ document_type.legal_status }}</p>
        <p class="card-text"><strong>Размеры:</strong> {{ document_type.length }} x {{ document_type.width }} см</p>
        <p class="card-text"><strong>Количество страниц:</strong> {{ document_type.pages }}</p>
        <p class="card-text"><strong>Срок действия:</strong> {{ document_type.validity_period }} лет</p>
        <p class="card-text"><strong>Возможность продления:</strong> {{ document_type.renewable|yesno:"Да,Нет" }}</p>
        <p class="card-text"><strong>Государство:</strong> {{ document_type.issuing_country.full_name }}</p>
    </div>
</div>

<h2 class="mb-3">Особенности документа</h2>
<ul class="list-group mb-4">
    {% for feature in document_type.features.all %}
        <li class="list-group-item">
            <h5>{{ feature.feature_name }}</h5>
            <ul>
                {% for detail in feature.details.all %}
                    <li>
                        <strong>{{ detail.key }}:</strong> {{ detail.value }}
                        {% if detail.image %}
                            <img src="{{ detail.image.url }}" alt="{{ detail.key }}" style="max-width: 200px; height: auto;">
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% empty %}
        <li class="list-group-item">Нет особенностей.</li>
    {% endfor %}
</ul>

<a href="{% url 'countries:country_detail' document_type.issuing_country.pk %}" class="btn btn-secondary">Назад к списку</a>
{% endblock %}

bghb/bghb/templates/documents/document_feature_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Добавить особенность для документа {{ document.name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}

bghb/bghb/templates/documents/document_type_detail.html
{% extends 'base.html' %}

{% block title %}{{ document_type.name }}{% endblock %}

{% block content %}
<div class="container mt-5">
    <!-- Заголовок -->
    <h1 class="mb-4">{{ document_type.name }} ({{ document_type.code }})</h1>

    <!-- Информация о типе документа -->
    <div class="card mb-4 shadow">
        <div class="card-header bg-primary text-white">
            <h5 class="card-title mb-0">Информация о типе документа</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <p class="card-text"><strong>Категория:</strong> {{ document_type.category|default:"Не указано" }}</p>
                    <p class="card-text"><strong>Тип:</strong> {{ document_type.type|default:"Не указано" }}</p>
                    <p class="card-text"><strong>Дата первой выдачи:</strong> {{ document_type.first_issue_date|default:"Не указано" }}</p>
                    <p class="card-text"><strong>Действующий:</strong> {{ document_type.valid|yesno:"Да,Нет" }}</p>
                </div>
                <div class="col-md-6">
                    <p class="card-text"><strong>Юридический статус:</strong> {{ document_type.legal_status|default:"Не указано" }}</p>
                    <p class="card-text"><strong>Размеры:</strong> {{ document_type.length|default:"Не указано" }} x {{ document_type.width|default:"Не указано" }} см</p>
                    <p class="card-text"><strong>Количество страниц:</strong> {{ document_type.pages|default:"Не указано" }}</p>
                    <p class="card-text"><strong>Срок действия:</strong> {{ document_type.validity_period|default:"Не указано" }} лет</p>
                    <p class="card-text"><strong>Возможность продления:</strong> {{ document_type.renewable|yesno:"Да,Нет" }}</p>
                </div>
            </div>
            <hr>
            <p class="card-text">
                <strong>Государство:</strong>
                {% if document_type.issuing_country %}
                    {{ document_type.issuing_country.full_name }}
                {% else %}
                    Не указано
                {% endif %}
            </p>
        </div>
    </div>

    <!-- Особенности документа -->
    <div class="card mb-4 shadow">
        <div class="card-header bg-success text-white">
            <h5 class="card-title mb-0">Особенности документа</h5>
        </div>
        <div class="card-body">
            {% if document_type.features.all %}
                <div class="accordion" id="featuresAccordion">
                    {% for feature in document_type.features.all %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                                    {{ feature.feature_name }}
                                </button>
                            </h2>
                            <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#featuresAccordion">
                                
                            <div class="accordion-body">

                                    <ul class="list-group list-group-flush">
                                        {% for detail in feature.details.all %}
                                      
                                        

                                        <li class="list-group-item">
                                            <div class="d-flex justify-content-between align-items-center">
                                                <div>
                                                    <strong>{{ detail.key }}:</strong> {{ detail.value }}
                                                    {% if detail.image %}
                                                        <div class="mt-2">
                                                            <img src="{{ detail.image.url }}" alt="{{ detail.key }}" class="img-fluid rounded" style="max-width: 100%; height: auto;">
                                                        </div>
                                                    {% endif %}
                                                </div>
                                                {% if user.is_staff %}
                                                    <a href="{% url 'documents:feature_detail_edit' pk=detail.pk %}" class="btn btn-sm btn-warning">Редактировать деталь</a>
                                                {% endif %}
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>

                                    {% if user.is_staff %}
                                        <div class="mt-3">
                                            <a href="{% url 'documents:feature_detail_add' feature_id=feature.pk %}" class="btn btn-sm btn-info">Добавить деталь</a>
                                            <a href="{% url 'documents:document_feature_edit' pk=feature.pk %}" class="btn btn-sm btn-warning">Редактировать особенность</a>
                                        </div>
                                    {% endif %}

                                </div>


                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p class="text-muted">Нет особенностей.</p>
            {% endif %}
        </div>
    </div>

    <!-- Кнопки действий -->
    <div class="text-center mb-4">
        {% if document_type.issuing_country %}
            <a href="{% url 'countries:country_detail' document_type.issuing_country.pk %}" class="btn btn-secondary">Назад к списку</a>
        {% else %}
            <p class="text-danger">Страна не назначена.</p>
        {% endif %}
        {% if user.is_staff %}
            <a href="{% url 'documents:document_feature_add' document_id=document_type.pk %}" class="btn btn-primary">Добавить особенность</a>
        {% endif %}
    </div>
</div>
{% endblock %}

bghb/bghb/templates/documents/document_type_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Добавить документ для {{ country.full_name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'home' %}" class="btn btn-outline-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

bghb/bghb/templates/documents/feature_detail_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Добавить деталь для особенности {{ feature.feature_name }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}